# Generated by Django 2.2 on 2019-10-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191001_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', 'updated', 'timestamp']},
        ),
    ]
